from . import admission_register
from . import student_count
from . import admission_summary
from . import matriculation_report
from . import nominal_roll
from . import monthly_admission_count
from . import student_detailed_report
from . import student_id_card
from . import cd_register
from . import fee_due
from . import programme_fee_collection
from . import fee_pending_list
from . import dfcr
from . import print_idcard
from . import batch_fee_load
from . import periodic_collection_summary
from . import applicant_rank_list
from . import student_attendance
from . import student_attendance_report
from . import attendance_summary_report
from . import scholarship_report