{
    'name': 'Employee Module',
    'version': '1.0',
    'summary': 'Custom Employee Module',
    'description': 'Custom Employee Module',
    'category': 'Employee',
    'author': 'Farook College',
    'website': 'https://farookcollege.ac.in/',
    'license': 'AGPL-3',
    'depends': ['hr_holidays', 'safi_students'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/duty_leave_report.xml',
        'report/leave_receipt.xml',
        'report/other_leave_report.xml',
        'report/report.xml',
        'report/retirement_list.xml',
        'report/employee_profile.xml',
        'report/employee_publication_report.xml',
        'views/hr.xml',
        'views/compensation_leave.xml',
        'views/staff_communication.xml',
        'views/student.xml',
        'views/hr_configurations.xml',
        'views/duty_rejoin.xml',
        'views/duty_entry.xml',
        'wizard/seniority_report.xml',
        'wizard/retirement_list.xml',
        'wizard/employee_profoma.xml',
        'wizard/employee_publication_report.xml',
        'wizard/print_idcard.xml'
    ],
    'installable': True,
    'auto_install': False
}
