{
    "name": "Student Management",
    "summary": """Student Related Module""",
    "version": "13.0.1.0.1",
    "category": "Academic",
    "license": "LGPL-3",
    "author": "Farook College",
    "website": "http://www.farookcollege.ac.in",
    "depends": [
        'mail', 'account', 'report_xlsx'
    ],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/report.xml',
        'report/custom_header.xml',
        'report/admission_register.xml',
        'report/cd_register.xml',
        'views/student.xml',
        'views/student_transfer.xml',
        'views/fee.xml',
        'views/tc_register.xml',
        'views/message_student.xml',
        'views/student_attendance.xml',
        'views/cd_adjustment.xml',
        'report/tc_printout.xml',
        'report/fee_receipt_printout.xml',
        'report/matriculation_report.xml',
        'report/nominal_roll.xml',
        'report/monthly_admission_count.xml',
        'report/applicant_rank_list.xml',
        'wizard/admission_register.xml',
        'wizard/student_count.xml',
        'wizard/admission_summary.xml',
        'wizard/matriculation_report.xml',
        'wizard/nominal_roll.xml',
        'wizard/monthly_admission_count.xml',
        'wizard/student_detailed_report.xml',
        'wizard/student_id_card.xml',
        'wizard/cd_register.xml',
        'wizard/fee_due.xml',
        'wizard/programme_fee_collection.xml',
        'wizard/fee_pending_list.xml',
        'wizard/dfcr.xml',
        'wizard/print_idcard.xml',
        'wizard/batch_fee_load.xml',
        'wizard/periodic_collection_summary.xml',
        'wizard/applicant_rank_list.xml',
        'wizard/student_attendance.xml',
        'wizard/student_attendance_report.xml',
        'wizard/attendance_summary_report.xml',
        'wizard/scholarship_report.xml',
    ],
    "images": [
        # 'static/description/banner.png'
    ],
    "application": False,
    "installable": True,
    'auto_install': False,
}